"""
Alert model — generated by the Detection Engine when a rule matches.
"""
from __future__ import annotations

import enum
import uuid
from typing import TYPE_CHECKING, List, Optional

from sqlalchemy import Enum as SAEnum
from sqlalchemy import ForeignKey, Index, String
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base, UUIDPKMixin, TimestampMixin

if TYPE_CHECKING:
    from app.models.detection_rule import DetectionRule
    from app.models.user import User
    from app.models.log import NormalizedLogEntry
    from app.models.incident import IncidentAlert
    from app.models.investigation_note import InvestigationNote
    from app.models.ioc import IOC


class AlertSeverity(str, enum.Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class AlertStatus(str, enum.Enum):
    OPEN = "Open"
    INVESTIGATING = "Investigating"
    CONTAINED = "Contained"
    RESOLVED = "Resolved"
    CLOSED = "Closed"


class AlertSource(str, enum.Enum):
    WINDOWS = "windows"
    LINUX = "linux"
    WEB_APPLICATION = "web_application"
    NETWORK = "network"


class Alert(UUIDPKMixin, TimestampMixin, Base):
    __tablename__ = "alerts"

    rule_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("detection_rules.id", ondelete="RESTRICT"), nullable=False
    )
    rule: Mapped["DetectionRule"] = relationship(back_populates="alerts")

    severity: Mapped[AlertSeverity] = mapped_column(
        SAEnum(AlertSeverity, name="alert_severity_enum", native_enum=True), nullable=False, index=True
    )
    status: Mapped[AlertStatus] = mapped_column(
        SAEnum(AlertStatus, name="alert_status_enum", native_enum=True),
        default=AlertStatus.OPEN,
        nullable=False,
        index=True,
    )
    source: Mapped[AlertSource] = mapped_column(
        SAEnum(AlertSource, name="alert_source_enum", native_enum=True), nullable=False
    )
    # Structured evidence snapshot: matched fields, counts, thresholds hit, etc.
    evidence: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)

    analyst_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )
    analyst: Mapped[Optional["User"]] = relationship(
        back_populates="assigned_alerts", foreign_keys=[analyst_id]
    )

    log_entry_links: Mapped[List["AlertLogEntry"]] = relationship(
        back_populates="alert", cascade="all, delete-orphan"
    )
    incident_links: Mapped[List["IncidentAlert"]] = relationship(back_populates="alert")
    notes: Mapped[List["InvestigationNote"]] = relationship(back_populates="alert")
    iocs: Mapped[List["IOC"]] = relationship(back_populates="related_alert")

    __table_args__ = (
        Index("ix_alerts_status_severity", "status", "severity"),
        Index("ix_alerts_created_at", "created_at"),
    )

    def __repr__(self) -> str:
        return f"<Alert {self.id} status={self.status} severity={self.severity}>"


class AlertLogEntry(Base):
    """Join table: which normalized log entries serve as evidence for an alert."""
    __tablename__ = "alert_log_entries"

    alert_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("alerts.id", ondelete="CASCADE"), primary_key=True
    )
    log_entry_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("normalized_log_entries.id", ondelete="CASCADE"), primary_key=True
    )

    alert: Mapped["Alert"] = relationship(back_populates="log_entry_links")
    log_entry: Mapped["NormalizedLogEntry"] = relationship(back_populates="alert_links")
