"""
DetectionRule model — configurable detection logic definitions.

Each rule expresses a set of simple match conditions (event_id, username,
source_ip, process_name, command_contains) that a future Detection Engine
will evaluate against normalized_log_entries. A null/unset condition field
means "don't filter on this field" — a rule only needs to set the fields
relevant to what it's detecting. Rule *execution* is intentionally not
implemented yet; this model only defines what a rule looks like.
"""
from __future__ import annotations

import enum
import uuid
from typing import TYPE_CHECKING, List, Optional

from sqlalchemy import Boolean, Enum as SAEnum
from sqlalchemy import ForeignKey, String, Text
from sqlalchemy.dialects.postgresql import INET, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base, UUIDPKMixin, TimestampMixin

if TYPE_CHECKING:
    from app.models.mitre_technique import MitreTechnique
    from app.models.alert import Alert


class RuleSeverity(str, enum.Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class DetectionRule(UUIDPKMixin, TimestampMixin, Base):
    __tablename__ = "detection_rules"

    name: Mapped[str] = mapped_column(String(150), unique=True, nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    enabled: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)

    # Severity assigned to alerts generated by this rule, once the
    # Detection Engine exists to generate them.
    severity: Mapped[RuleSeverity] = mapped_column(
        SAEnum(
            RuleSeverity,
            name="rule_severity_enum",
            native_enum=True,
            values_callable=lambda e: [item.value for item in e],
        ),
        nullable=False,
    )

    # --- Match conditions -------------------------------------------------
    # All optional: a rule sets only the fields relevant to what it's
    # matching against normalized_log_entries. event_id/username/
    # process_name mirror the column sizes on NormalizedLogEntry;
    # source_ip is INET for the same reason (consistent, DB-validated
    # exact-match comparison). command_contains is a substring match
    # against normalized_log_entries.command_line, not an exact match.
    event_id: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    username: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    source_ip: Mapped[Optional[str]] = mapped_column(INET, nullable=True)
    process_name: Mapped[Optional[str]] = mapped_column(String(500), nullable=True)
    command_contains: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # Preserved from the original schema: MitreTechnique.detection_rules
    # and Alert.rule both depend on these relationships existing here.
    mitre_technique_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("mitre_techniques.id", ondelete="SET NULL"), nullable=True
    )
    mitre_technique: Mapped[Optional["MitreTechnique"]] = relationship(back_populates="detection_rules")

    alerts: Mapped[List["Alert"]] = relationship(back_populates="rule")

    def __repr__(self) -> str:
        return f"<DetectionRule {self.name}>"
